config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	 belongs_to :user

     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = current_user.profiles.build
  end

  def edit
  end

  def create
    @profile = current_user.profiles.build(profile_params)
      if @profile.save
        redirect_to @profile, notice: 'Profile was successfully created.'
      else
        render action: 'new' 
      end
    end

  def update
      if @profile.update(profile_params)
        redirect_to @profile, notice: 'Profile was successfully updated.'
      else
        render:'edit'
      end
    end

  def destroy
    @profile.destroy
      redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def correct_user
      @profile = current_user.profiles.find_by(id: params[:id])
      redirect_to profiles_path, notice: "Not authorized to edit this profile" if @profile.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:about, :breed, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default" role="footer">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <a class="navbar-brand" href="http://builditinteractive.com" target="_blank" >Designed by Buildit Interactive</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Purrr'fect match", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Profiles", profiles_path %></li> 
      <li><%= link_to "Contact", contact_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
       <li><%= link_to "Account", edit_user_registration_path %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- Containter -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Purrr'fect Match</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
		  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
			<%= yield %>
		</div>

	</body>
	<footer>
		<%= render 'layouts/footer' %>
	</footer>
</html>

app/views/pages/about.html.erb
<div class="jumbotron center">
<h1>About Us</h1>
<p>The Nations #1 Cat Dating Site!</h1>
</div>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Purrr'fect Match</h1>

	<% if user_signed_in? %>
		<p>Your a Cool Cat Meow!</p>
	<% else %>
		<%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	<% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= f.label :about %>
    <%= f.text_field :about, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :breed %>
    <%= f.text_field :breed, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="form-group">
  <% if user_signed_in? %>
    <%= link_to raw('<span class="glyphicon glyphicon-heart"></span> New Profile'), new_profile_path, class: "form-group btn btn-primary btn-lg"%>
  <% else %>
    <div class="jumbotron center">
            <h1>Don't Waste your Nine Lives Waiting!</h1>
            <h2>Sign Up Today to Find Your Purrr'fect Match!</h2>
            <br>
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

<div id="profiles" class="transitions-enabled">
  <% @profiles.each do |profile| %>
    <div class="box panel panel-default">
        <%= link_to image_tag(profile.image.url(:medium)), profile %>
        <div class="panel-body">
            <%= profile.about %>
            <%= profile.breed %>
            <br>
            <strong><%= profile.user.email if profile.user %></strong>
      <% if profile.user == current_user %>
        <div class="actions">
          <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit'), edit_profile_path(profile), class: "form-group" %>
          <%= link_to raw('<span class="glyphicon glyphicon-fire"></span> Destroy'), profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "form-group" %>
        </div>
      <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="form-group">
	<h1>New profile</h1>
</div>

<%= render 'form' %>

<div class="form-group">
<%= link_to 'Back', profiles_path,  class: "form-group"%>
</div>

app/views/profiles/show.html.erb
<div class="row">
	<div class="col-md-offset-1 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= image_tag @profile.image.url(:medium) %>
			</div>
			<div class="panel-body">
			<p class="form-group">
			  <strong>About:</strong>
			  <%= @profile.about %>
			</p>

			<p class="form-group">
			  <strong>Breed:</strong>
			  <%= @profile.breed %>
			</p>

			<p class="form-group">
			  <strong>Email:</strong>
			  <%= @profile.user.email if @profile.user %>
			</p>

			<div class="form-group">
				<% if @profile.user == current_user %>
				<%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit'), edit_profile_path(@profile), class: "form-group" %> |
				<% end %>
				<%= link_to raw('<span class="glyphicon glyphicon-share-alt"></span> Back'), profiles_path, class: "form-group" %>
				</div>
			</div>
		</div>
	</div>
</div>